[package]
name = "clustering-rust-example"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.38", features = ["lazy", "ndarray", "csv"] }
ndarray = "0.15"
linfa = "0.7.0"
linfa-clustering = "0.7.0"
plotters = "0.3.5"
rand = "0.8"
rand_distr = "0.4"